export interface MockPost {
  id: string;
  title: string;
  description: string | null;
  category: string;
  thumbnailUrl: string | null;
  viewCount: number;
  createdAt: string;
  author: { id: string; nickname: string | null; image: string | null };
  artist: { id: string; name: string } | null;
  reactionCount: number;
  commentCount: number;
  myReactions: string[];
  cheerCount?: number;
  aiScore?: number;
  gradient?: string;
}

export const MOCK_POSTS: MockPost[] = [
  {
    id: "mock-1",
    title: "Dynamite Lo-Fi 감성 리믹스",
    description: "BTS Dynamite를 로파이 힙합 스타일로 재해석했습니다. 새벽감성 가득!",
    category: "REMIX",
    thumbnailUrl: "/images/1.png",
    viewCount: 12340,
    createdAt: "2026-03-17T08:30:00Z",
    author: { id: "u1", nickname: "방탄프로듀서", image: null },
    artist: { id: "a1", name: "BTS" },
    reactionCount: 342,
    commentCount: 45,
    myReactions: [],
    cheerCount: 210,
    aiScore: 89,
    gradient: "from-violet-600 to-indigo-600",
  },
  {
    id: "mock-2",
    title: "에스파 카리나 버추얼 팬아트",
    description: "사이버펑크 컨셉으로 만든 카리나 AI 일러스트",
    category: "VIRTUAL",
    thumbnailUrl: "/images/2.png",
    viewCount: 8920,
    createdAt: "2026-03-17T06:15:00Z",
    author: { id: "u2", nickname: "MY덕질일상", image: null },
    artist: { id: "a2", name: "aespa" },
    reactionCount: 287,
    commentCount: 38,
    myReactions: [],
    cheerCount: 180,
    aiScore: 92,
    gradient: "from-cyan-500 to-blue-600",
  },
  {
    id: "mock-3",
    title: "뉴진스 'ETA' 미래도시 컨셉 키트",
    description: "Y2K + 미래도시 무드로 만든 앨범 컨셉 디자인 패키지",
    category: "CONCEPT",
    thumbnailUrl: "/images/3.png",
    viewCount: 15670,
    createdAt: "2026-03-16T22:00:00Z",
    author: { id: "u3", nickname: "디자인버니", image: null },
    artist: { id: "a3", name: "NewJeans" },
    reactionCount: 456,
    commentCount: 67,
    myReactions: [],
    cheerCount: 300,
    aiScore: 95,
    gradient: "from-sky-400 to-emerald-400",
  },
  {
    id: "mock-4",
    title: "IVE 'HEYA' 칼군무 포메이션 기획",
    description: "6인 포메이션 전환 3장면, 센터 교체 동선 포함",
    category: "PERFORMANCE",
    thumbnailUrl: "/images/4.png",
    viewCount: 6780,
    createdAt: "2026-03-16T18:30:00Z",
    author: { id: "u4", nickname: "안무장인", image: null },
    artist: { id: "a4", name: "IVE" },
    reactionCount: 198,
    commentCount: 23,
    myReactions: [],
    cheerCount: 120,
    aiScore: 78,
    gradient: "from-rose-500 to-orange-400",
  },
  {
    id: "mock-5",
    title: "AI로 만든 7인조 보이그룹 'CHRONOS'",
    description: "시간여행 세계관, 멤버별 능력 설정까지 완성된 기획서",
    category: "IDOL_PROJECT",
    thumbnailUrl: "/images/5.jpg",
    viewCount: 23450,
    createdAt: "2026-03-16T14:00:00Z",
    author: { id: "u5", nickname: "기획의신", image: null },
    artist: null,
    reactionCount: 512,
    commentCount: 78,
    myReactions: [],
    cheerCount: 350,
    aiScore: 97,
    gradient: "from-purple-600 to-pink-500",
  },
  {
    id: "mock-6",
    title: "블랙핑크 'Pink Venom' 일본어 자막",
    description: "뮤비 전체 가사 + 멤버 대사 일본어 번역 완료",
    category: "GLOBAL_SYNC",
    thumbnailUrl: "/images/6.jpg",
    viewCount: 34210,
    createdAt: "2026-03-16T10:00:00Z",
    author: { id: "u6", nickname: "글로벌블링크", image: null },
    artist: { id: "a5", name: "BLACKPINK" },
    reactionCount: 389,
    commentCount: 52,
    myReactions: [],
    cheerCount: 240,
    aiScore: 88,
    gradient: "from-pink-500 to-yellow-400",
  },
  {
    id: "mock-7",
    title: "세븐틴 'Super' 트로피컬 리믹스",
    description: "여름 바이브 가득한 트로피컬 하우스 버전으로 재탄생",
    category: "REMIX",
    thumbnailUrl: "/images/7.jpg",
    viewCount: 9870,
    createdAt: "2026-03-15T20:30:00Z",
    author: { id: "u7", nickname: "캐럿DJ", image: null },
    artist: { id: "a6", name: "SEVENTEEN" },
    reactionCount: 234,
    commentCount: 31,
    myReactions: [],
    cheerCount: 156,
    aiScore: 84,
    gradient: "from-amber-400 to-red-500",
  },
  {
    id: "mock-8",
    title: "르세라핌 사쿠라 판타지 일러스트",
    description: "벚꽃 판타지 세계관으로 그린 사쿠라 AI 아트",
    category: "VIRTUAL",
    thumbnailUrl: "/images/8.jpg",
    viewCount: 11230,
    createdAt: "2026-03-15T16:45:00Z",
    author: { id: "u8", nickname: "피어나라", image: null },
    artist: { id: "a7", name: "LE SSERAFIM" },
    reactionCount: 367,
    commentCount: 44,
    myReactions: [],
    cheerCount: 230,
    aiScore: 91,
    gradient: "from-pink-400 to-rose-600",
  },
  {
    id: "mock-9",
    title: "스트레이 키즈 다크 앨범 컨셉 디자인",
    description: "고딕 호러 무드의 앨범 커버 + 로고 + 키비주얼 세트",
    category: "CONCEPT",
    thumbnailUrl: "/images/9.png",
    viewCount: 7650,
    createdAt: "2026-03-15T12:00:00Z",
    author: { id: "u9", nickname: "스키즈아트", image: null },
    artist: { id: "a8", name: "Stray Kids" },
    reactionCount: 276,
    commentCount: 35,
    myReactions: [],
    cheerCount: 170,
    aiScore: 86,
    gradient: "from-gray-700 to-red-900",
  },
  {
    id: "mock-10",
    title: "(여자)아이들 'Queencard' 포메이션",
    description: "5인 버전 퀸카드 안무 포메이션 + 조명 연출 기획",
    category: "PERFORMANCE",
    thumbnailUrl: "/images/10.jpg",
    viewCount: 5430,
    createdAt: "2026-03-15T08:20:00Z",
    author: { id: "u10", nickname: "네버랜드댄서", image: null },
    artist: { id: "a9", name: "(G)I-DLE" },
    reactionCount: 167,
    commentCount: 19,
    myReactions: [],
    cheerCount: 98,
    aiScore: 75,
    gradient: "from-fuchsia-500 to-purple-700",
  },
  {
    id: "mock-11",
    title: "5인조 걸그룹 'STELLAR' 기획서",
    description: "우주 탐험 세계관, 각 멤버가 다른 행성 출신 설정",
    category: "IDOL_PROJECT",
    thumbnailUrl: "/images/11.jpg",
    viewCount: 18900,
    createdAt: "2026-03-14T23:00:00Z",
    author: { id: "u11", nickname: "프로듀서101", image: null },
    artist: null,
    reactionCount: 423,
    commentCount: 61,
    myReactions: [],
    cheerCount: 280,
    aiScore: 93,
    gradient: "from-indigo-500 to-cyan-400",
  },
  {
    id: "mock-12",
    title: "NMIXX 'Dash' 스페인어 번역 자막",
    description: "라틴 팬들을 위한 Dash 풀버전 스페인어 자막",
    category: "GLOBAL_SYNC",
    thumbnailUrl: "/images/12.jpg",
    viewCount: 4560,
    createdAt: "2026-03-14T19:30:00Z",
    author: { id: "u12", nickname: "라틴엔믹서", image: null },
    artist: { id: "a10", name: "NMIXX" },
    reactionCount: 134,
    commentCount: 16,
    myReactions: [],
    cheerCount: 87,
    aiScore: 72,
    gradient: "from-orange-500 to-yellow-400",
  },
  {
    id: "mock-13",
    title: "뉴진스 'Hype Boy' 어쿠스틱 리믹스",
    description: "기타와 피아노만으로 재편곡한 감성 버전",
    category: "REMIX",
    thumbnailUrl: "/images/13.jpg",
    viewCount: 28900,
    createdAt: "2026-03-14T15:00:00Z",
    author: { id: "u13", nickname: "하입보이즈", image: null },
    artist: { id: "a3", name: "NewJeans" },
    reactionCount: 478,
    commentCount: 72,
    myReactions: [],
    cheerCount: 320,
    aiScore: 94,
    gradient: "from-blue-400 to-violet-500",
  },
  {
    id: "mock-14",
    title: "BTS 정국 레트로 스타일 AI 아트",
    description: "80년대 레트로 감성으로 재해석한 정국 비주얼",
    category: "VIRTUAL",
    thumbnailUrl: "/images/14.png",
    viewCount: 42100,
    createdAt: "2026-03-14T11:00:00Z",
    author: { id: "u14", nickname: "아미아티스트", image: null },
    artist: { id: "a1", name: "BTS" },
    reactionCount: 498,
    commentCount: 58,
    myReactions: [],
    cheerCount: 340,
    aiScore: 96,
    gradient: "from-yellow-400 to-pink-500",
  },
  {
    id: "mock-15",
    title: "IVE 청량 여름 앨범 컨셉 키트",
    description: "파스텔 블루 톤의 여름 미니앨범 디자인 세트",
    category: "CONCEPT",
    thumbnailUrl: "/images/15.jpg",
    viewCount: 13450,
    createdAt: "2026-03-13T20:00:00Z",
    author: { id: "u15", nickname: "다이브디자이너", image: null },
    artist: { id: "a4", name: "IVE" },
    reactionCount: 312,
    commentCount: 42,
    myReactions: [],
    cheerCount: 200,
    aiScore: 87,
    gradient: "from-teal-400 to-blue-400",
  },
  {
    id: "mock-16",
    title: "에스파 'Supernova' 4인 칼군무 기획",
    description: "우주 스테이지 컨셉, LED 바닥 연출 포함 포메이션",
    category: "PERFORMANCE",
    thumbnailUrl: "/images/16.jpg",
    viewCount: 8760,
    createdAt: "2026-03-13T16:00:00Z",
    author: { id: "u16", nickname: "광야안무가", image: null },
    artist: { id: "a2", name: "aespa" },
    reactionCount: 245,
    commentCount: 29,
    myReactions: [],
    cheerCount: 158,
    aiScore: 82,
    gradient: "from-violet-500 to-fuchsia-500",
  },
  {
    id: "mock-17",
    title: "AI 혼성 그룹 'PRISM' 데뷔 기획",
    description: "빛의 스펙트럼 세계관, 남녀 혼성 6인조 기획서 완성",
    category: "IDOL_PROJECT",
    thumbnailUrl: "/images/1.png",
    viewCount: 31200,
    createdAt: "2026-03-13T12:00:00Z",
    author: { id: "u17", nickname: "히트메이커", image: null },
    artist: null,
    reactionCount: 467,
    commentCount: 73,
    myReactions: [],
    cheerCount: 310,
    aiScore: 95,
    gradient: "from-red-500 to-blue-500",
  },
  {
    id: "mock-18",
    title: "세븐틴 'HOT' 중국어 번역 자막",
    description: "중국 캐럿을 위한 HOT 뮤비 간체 자막 완성",
    category: "GLOBAL_SYNC",
    thumbnailUrl: "/images/2.png",
    viewCount: 7890,
    createdAt: "2026-03-12T22:00:00Z",
    author: { id: "u18", nickname: "차이나캐럿", image: null },
    artist: { id: "a6", name: "SEVENTEEN" },
    reactionCount: 198,
    commentCount: 24,
    myReactions: [],
    cheerCount: 130,
    aiScore: 79,
    gradient: "from-red-600 to-amber-400",
  },
  {
    id: "mock-19",
    title: "블랙핑크 'Shut Down' EDM 리믹스",
    description: "하드스타일 EDM으로 재탄생한 셧다운, 클럽 버전",
    category: "REMIX",
    thumbnailUrl: "/images/3.png",
    viewCount: 19870,
    createdAt: "2026-03-12T18:00:00Z",
    author: { id: "u19", nickname: "블링크비트", image: null },
    artist: { id: "a5", name: "BLACKPINK" },
    reactionCount: 389,
    commentCount: 47,
    myReactions: [],
    cheerCount: 250,
    aiScore: 90,
    gradient: "from-pink-600 to-black",
  },
  {
    id: "mock-20",
    title: "르세라핌 다크 판타지 컨셉 앨범",
    description: "뱀파이어 x 고딕 세계관의 미니앨범 풀 디자인",
    category: "CONCEPT",
    thumbnailUrl: "/images/4.png",
    viewCount: 16340,
    createdAt: "2026-03-12T14:00:00Z",
    author: { id: "u20", nickname: "피어니컨셉러", image: null },
    artist: { id: "a7", name: "LE SSERAFIM" },
    reactionCount: 356,
    commentCount: 48,
    myReactions: [],
    cheerCount: 220,
    aiScore: 88,
    gradient: "from-red-800 to-purple-900",
  },
];
