export interface MockPost {
  id: string;
  title: string;
  description: string | null;
  category: string;
  thumbnailUrl: string | null;
  viewCount: number;
  createdAt: string;
  author: { id: string; nickname: string | null; image: string | null };
  artist: { id: string; name: string } | null;
  reactionCount: number;
  commentCount: number;
  myReactions: string[];
  cheerCount?: number;
  aiScore?: number;
  gradient?: string;
}

export const MOCK_POSTS: MockPost[] = [
  {
    id: "mock-2",
    title: "사이버펑크 버추얼 아이돌 팬아트",
    description: "사이버펑크 컨셉으로 만든 버추얼 아이돌 AI 일러스트",
    category: "VIRTUAL",
    thumbnailUrl: null,
    viewCount: 8920,
    createdAt: "2026-03-17T06:15:00Z",
    author: { id: "u2", nickname: "MY덕질일상", image: null },
    artist: null,
    reactionCount: 287,
    commentCount: 38,
    myReactions: [],
    cheerCount: 180,
    aiScore: 92,
    gradient: "from-cyan-500 to-blue-600",
  },
  {
    id: "mock-3",
    title: "미래도시 컨셉 키트 디자인",
    description: "Y2K + 미래도시 무드로 만든 앨범 컨셉 디자인 패키지",
    category: "CONCEPT",
    thumbnailUrl: null,
    viewCount: 15670,
    createdAt: "2026-03-16T22:00:00Z",
    author: { id: "u3", nickname: "디자인버니", image: null },
    artist: null,
    reactionCount: 456,
    commentCount: 67,
    myReactions: [],
    cheerCount: 300,
    aiScore: 95,
    gradient: "from-sky-400 to-emerald-400",
  },
  {
    id: "mock-4",
    title: "6인조 걸그룹 칼군무 포메이션 기획",
    description: "6인 포메이션 전환 3장면, 센터 교체 동선 포함",
    category: "PERFORMANCE",
    thumbnailUrl: null,
    viewCount: 6780,
    createdAt: "2026-03-16T18:30:00Z",
    author: { id: "u4", nickname: "안무장인", image: null },
    artist: null,
    reactionCount: 198,
    commentCount: 23,
    myReactions: [],
    cheerCount: 120,
    aiScore: 78,
    gradient: "from-rose-500 to-orange-400",
  },
  {
    id: "mock-5",
    title: "AI로 만든 7인조 보이그룹 'CHRONOS'",
    description: "시간여행 세계관, 멤버별 능력 설정까지 완성된 기획서",
    category: "IDOL_PROJECT",
    thumbnailUrl: null,
    viewCount: 23450,
    createdAt: "2026-03-16T14:00:00Z",
    author: { id: "u5", nickname: "기획의신", image: null },
    artist: null,
    reactionCount: 512,
    commentCount: 78,
    myReactions: [],
    cheerCount: 350,
    aiScore: 97,
    gradient: "from-purple-600 to-pink-500",
  },
  {
    id: "mock-6",
    title: "가상 걸그룹 뮤비 일본어 자막",
    description: "뮤비 전체 가사 + 멤버 대사 일본어 번역 완료",
    category: "GLOBAL_SYNC",
    thumbnailUrl: null,
    viewCount: 34210,
    createdAt: "2026-03-16T10:00:00Z",
    author: { id: "u6", nickname: "글로벌팬", image: null },
    artist: null,
    reactionCount: 389,
    commentCount: 52,
    myReactions: [],
    cheerCount: 240,
    aiScore: 88,
    gradient: "from-pink-500 to-yellow-400",
  },
  {
    id: "mock-8",
    title: "벚꽃 판타지 버추얼 아이돌 일러스트",
    description: "벚꽃 판타지 세계관으로 그린 버추얼 아이돌 AI 아트",
    category: "VIRTUAL",
    thumbnailUrl: null,
    viewCount: 11230,
    createdAt: "2026-03-15T16:45:00Z",
    author: { id: "u8", nickname: "피어나라", image: null },
    artist: null,
    reactionCount: 367,
    commentCount: 44,
    myReactions: [],
    cheerCount: 230,
    aiScore: 91,
    gradient: "from-pink-400 to-rose-600",
  },
  {
    id: "mock-9",
    title: "다크 고딕 앨범 컨셉 디자인",
    description: "고딕 호러 무드의 앨범 커버 + 로고 + 키비주얼 세트",
    category: "CONCEPT",
    thumbnailUrl: null,
    viewCount: 7650,
    createdAt: "2026-03-15T12:00:00Z",
    author: { id: "u9", nickname: "컨셉아트", image: null },
    artist: null,
    reactionCount: 276,
    commentCount: 35,
    myReactions: [],
    cheerCount: 170,
    aiScore: 86,
    gradient: "from-gray-700 to-red-900",
  },
  {
    id: "mock-10",
    title: "5인조 걸그룹 퍼포먼스 포메이션",
    description: "5인 버전 안무 포메이션 + 조명 연출 기획",
    category: "PERFORMANCE",
    thumbnailUrl: null,
    viewCount: 5430,
    createdAt: "2026-03-15T08:20:00Z",
    author: { id: "u10", nickname: "네버랜드댄서", image: null },
    artist: null,
    reactionCount: 167,
    commentCount: 19,
    myReactions: [],
    cheerCount: 98,
    aiScore: 75,
    gradient: "from-fuchsia-500 to-purple-700",
  },
  {
    id: "mock-11",
    title: "5인조 걸그룹 'STELLAR' 기획서",
    description: "우주 탐험 세계관, 각 멤버가 다른 행성 출신 설정",
    category: "IDOL_PROJECT",
    thumbnailUrl: null,
    viewCount: 18900,
    createdAt: "2026-03-14T23:00:00Z",
    author: { id: "u11", nickname: "프로듀서101", image: null },
    artist: null,
    reactionCount: 423,
    commentCount: 61,
    myReactions: [],
    cheerCount: 280,
    aiScore: 93,
    gradient: "from-indigo-500 to-cyan-400",
  },
  {
    id: "mock-12",
    title: "가상 걸그룹 스페인어 번역 자막",
    description: "라틴 팬들을 위한 풀버전 스페인어 자막",
    category: "GLOBAL_SYNC",
    thumbnailUrl: null,
    viewCount: 4560,
    createdAt: "2026-03-14T19:30:00Z",
    author: { id: "u12", nickname: "라틴팬", image: null },
    artist: null,
    reactionCount: 134,
    commentCount: 16,
    myReactions: [],
    cheerCount: 87,
    aiScore: 72,
    gradient: "from-orange-500 to-yellow-400",
  },
  {
    id: "mock-14",
    title: "레트로 스타일 버추얼 아이돌 AI 아트",
    description: "80년대 레트로 감성으로 재해석한 버추얼 아이돌 비주얼",
    category: "VIRTUAL",
    thumbnailUrl: null,
    viewCount: 42100,
    createdAt: "2026-03-14T11:00:00Z",
    author: { id: "u14", nickname: "아트마스터", image: null },
    artist: null,
    reactionCount: 498,
    commentCount: 58,
    myReactions: [],
    cheerCount: 340,
    aiScore: 96,
    gradient: "from-yellow-400 to-pink-500",
  },
  {
    id: "mock-15",
    title: "청량 여름 앨범 컨셉 키트",
    description: "파스텔 블루 톤의 여름 미니앨범 디자인 세트",
    category: "CONCEPT",
    thumbnailUrl: null,
    viewCount: 13450,
    createdAt: "2026-03-13T20:00:00Z",
    author: { id: "u15", nickname: "다이브디자이너", image: null },
    artist: null,
    reactionCount: 312,
    commentCount: 42,
    myReactions: [],
    cheerCount: 200,
    aiScore: 87,
    gradient: "from-teal-400 to-blue-400",
  },
  {
    id: "mock-16",
    title: "4인조 우주 스테이지 퍼포먼스 기획",
    description: "우주 스테이지 컨셉, LED 바닥 연출 포함 포메이션",
    category: "PERFORMANCE",
    thumbnailUrl: null,
    viewCount: 8760,
    createdAt: "2026-03-13T16:00:00Z",
    author: { id: "u16", nickname: "안무가", image: null },
    artist: null,
    reactionCount: 245,
    commentCount: 29,
    myReactions: [],
    cheerCount: 158,
    aiScore: 82,
    gradient: "from-violet-500 to-fuchsia-500",
  },
  {
    id: "mock-17",
    title: "AI 혼성 그룹 'PRISM' 데뷔 기획",
    description: "빛의 스펙트럼 세계관, 남녀 혼성 6인조 기획서 완성",
    category: "IDOL_PROJECT",
    thumbnailUrl: null,
    viewCount: 31200,
    createdAt: "2026-03-13T12:00:00Z",
    author: { id: "u17", nickname: "히트메이커", image: null },
    artist: null,
    reactionCount: 467,
    commentCount: 73,
    myReactions: [],
    cheerCount: 310,
    aiScore: 95,
    gradient: "from-red-500 to-blue-500",
  },
  {
    id: "mock-18",
    title: "가상 보이그룹 중국어 번역 자막",
    description: "중국 팬을 위한 뮤비 간체 자막 완성",
    category: "GLOBAL_SYNC",
    thumbnailUrl: null,
    viewCount: 7890,
    createdAt: "2026-03-12T22:00:00Z",
    author: { id: "u18", nickname: "차이나팬", image: null },
    artist: null,
    reactionCount: 198,
    commentCount: 24,
    myReactions: [],
    cheerCount: 130,
    aiScore: 79,
    gradient: "from-red-600 to-amber-400",
  },
  {
    id: "mock-20",
    title: "다크 판타지 컨셉 앨범 디자인",
    description: "뱀파이어 x 고딕 세계관의 미니앨범 풀 디자인",
    category: "CONCEPT",
    thumbnailUrl: null,
    viewCount: 16340,
    createdAt: "2026-03-12T14:00:00Z",
    author: { id: "u20", nickname: "컨셉러", image: null },
    artist: null,
    reactionCount: 356,
    commentCount: 48,
    myReactions: [],
    cheerCount: 220,
    aiScore: 88,
    gradient: "from-red-800 to-purple-900",
  },
];
